version: '3.7'

x-default-opts:
  &default-opts
  logging:
    options:
      max-size: "1m"

services:
  scanner:
    <<: *default-opts
    image: registry.undernet.antipathy.org/fingscanner:latest
    networks:
      - monitoring
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      SUBNET: "192.168.0.1/24"
      INFLUX_SERVER: "stats.${DOMAIN?Variable not set}"
      INFLUX_TOKEN: ${INFLUX_TOKEN?Variable not set}
      INFLUX_ORG: ${DOMAIN?Variable not set}
      INFLUX_BUCKET: monitoring
      DNS_SERVER: "8.8.8.8"
      LOG_SERVER: "logs.${DOMAIN?Variable not set}"
      ACTOR_POOL: "10"
      SCHEDULE: "10"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
      placement:
        constraints:
          - node.labels.fing.fing-data == true
networks:
  monitoring:
    external: true
